language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t alexandersubota/fibsq -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true alexandersubota/fibsq npm test
    
after_success:
    - docker build -t alexandersubota/multi-client ./client 
    - docker build -t alexandersubota/multi-nginx ./nginx
    - docker build -t alexandersubota/multi-server ./server
    - docker build -t alexandersubota/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push alexandersubota/multi-client
    - docker push alexandersubota/multi-nginx
    - docker push alexandersubota/multi-server
    - docker push alexandersubota/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: Multi-container
    bucket_name: elasticbeanstalk-us-east-1-602281756836
    bycket_path: docker-multi
    on:
        branch: master
    access_key_id: 
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        seure: $AWS_SECRET_KEY
        